# Generated by Django 5.2.8 on 2025-11-17 18:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='crawljob',
            name='core_crawlj_status_6473ab_idx',
        ),
        migrations.RemoveIndex(
            model_name='crawljob',
            name='core_crawlj_client__e72a1d_idx',
        ),
        migrations.AddField(
            model_name='crawljob',
            name='analysis_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawljob',
            name='duplicate_pages',
            field=models.IntegerField(default=0, help_text='The number of duplicate pages crawled'),
        ),
        migrations.AddField(
            model_name='crawljob',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawljob',
            name='exclude_patterns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='List of patterns to exclude from the crawl', size=None),
        ),
        migrations.AddField(
            model_name='crawljob',
            name='include_patterns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='List of patterns to include in the crawl', size=None),
        ),
        migrations.AddField(
            model_name='crawljob',
            name='is_analyzed',
            field=models.BooleanField(default=False, help_text='Whether the crawl has been analyzed'),
        ),
        migrations.AddField(
            model_name='crawljob',
            name='max_depth',
            field=models.IntegerField(default=10, help_text='The maximum depth to crawl'),
        ),
        migrations.AddField(
            model_name='crawljob',
            name='max_pages',
            field=models.IntegerField(default=50000, help_text='The maximum number of pages to crawl'),
        ),
        migrations.AddField(
            model_name='crawljob',
            name='pages_crawled',
            field=models.IntegerField(default=0, help_text='The number of pages crawled'),
        ),
        migrations.AddField(
            model_name='crawljob',
            name='pages_failed',
            field=models.IntegerField(default=0, help_text='The number of pages that failed to crawl'),
        ),
        migrations.AddField(
            model_name='crawljob',
            name='rate_limit',
            field=models.FloatField(default=1.0, help_text='The rate limit in requests per second'),
        ),
        migrations.AddField(
            model_name='crawljob',
            name='unique_content_pages',
            field=models.IntegerField(default=0, help_text='The number of unique content pages crawled'),
        ),
        migrations.AddField(
            model_name='crawljob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['status', 'created_at'], name='core_crawlj_status_dfef28_idx'),
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['client', 'status'], name='core_crawlj_client__5e1614_idx'),
        ),
    ]
