# Generated by Django 5.2.8 on 2025-11-18 04:07

from django.db import migrations


def rename_column_forward(apps, schema_editor):
    """Rename the misspelled column to the correct spelling"""
    schema_editor.execute(
        'ALTER TABLE core_crawljob RENAME COLUMN unigue_content_pages TO unique_content_pages;'
    )


def rename_column_backward(apps, schema_editor):
    """Revert the column name back (for rollback)"""
    schema_editor.execute(
        'ALTER TABLE core_crawljob RENAME COLUMN unique_content_pages TO unigue_content_pages;'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_crawljob_core_crawlj_status_6473ab_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(rename_column_forward, rename_column_backward),
    ]
