# Generated by Django 5.2.8 on 2025-11-16 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=2048)),
                ('depth', models.IntegerField(default=0, help_text='Depth from the starting URL')),
                ('title', models.CharField(blank=True, max_length=512)),
                ('main_content', models.TextField(help_text='Cleaned main content text without nav/headers/footers')),
                ('raw_html', models.TextField(blank=True, help_text='Optional raw HTML for reprocessing', null=True)),
                ('code_blocks', models.JSONField(default=list, help_text='List of code blocks with language and content')),
                ('internal_links', models.JSONField(default=list, help_text='List of internal links found on this page')),
                ('external_links', models.JSONField(default=list, help_text='List of external links found on this page')),
                ('headers', models.JSONField(default=dict, help_text='Dictionary of headers (h1-h6) found on this page')),
                ('meta_description', models.TextField(blank=True)),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 hash of main_content for deduplication', max_length=64)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('page_size', models.IntegerField(blank=True, help_text='Page size in bytes', null=True)),
                ('status_code', models.IntegerField(default=200)),
                ('crawled_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('requires_javascript', models.BooleanField(default=False, help_text='Whether this page required JavaScript rendering')),
                ('is_duplicate', models.BooleanField(default=False, help_text='Whether this page is a duplicate of another')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.crawljob')),
            ],
            options={
                'ordering': ['-crawled_at'],
                'indexes': [models.Index(fields=['job', '-crawled_at'], name='crawler_cra_job_id_08bb70_idx'), models.Index(fields=['job', 'url'], name='crawler_cra_job_id_2eadef_idx'), models.Index(fields=['job', 'content_hash'], name='crawler_cra_job_id_88deea_idx'), models.Index(fields=['job', 'depth'], name='crawler_cra_job_id_6b65b3_idx')],
                'unique_together': {('job', 'url')},
            },
        ),
        migrations.CreateModel(
            name='CrawlError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('error_type', models.CharField(choices=[('timeout', 'Timeout'), ('http_error', 'HTTP Error'), ('connection_error', 'Connection Error'), ('parse_error', 'Parse Error'), ('javascript_error', 'JavaScript Error'), ('other', 'Other')], max_length=50)),
                ('error_message', models.TextField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('depth', models.IntegerField(default=0)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='core.crawljob')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job', '-created_at'], name='crawler_cra_job_id_e09680_idx'), models.Index(fields=['job', 'error_type'], name='crawler_cra_job_id_e9158f_idx')],
            },
        ),
    ]
