# Generated by Django 5.2.8 on 2025-11-17 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_crawljob_core_crawlj_status_6473ab_idx_and_more'),
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('parent', 'Parent Page'), ('child', 'Child Page'), ('sibling', 'Sibling Page'), ('related', 'Related Page'), ('next', 'Next Page'), ('previous', 'Previous Page')], max_length=20)),
                ('anchor_text', models.TextField(blank=True)),
                ('context', models.TextField(blank=True, help_text='Surrounding text near the link')),
            ],
        ),
        migrations.AlterModelOptions(
            name='crawledpage',
            options={'ordering': ['depth', 'url']},
        ),
        migrations.RemoveIndex(
            model_name='crawledpage',
            name='crawler_cra_job_id_08bb70_idx',
        ),
        migrations.RemoveIndex(
            model_name='crawledpage',
            name='crawler_cra_job_id_2eadef_idx',
        ),
        migrations.RemoveIndex(
            model_name='crawledpage',
            name='crawler_cra_job_id_88deea_idx',
        ),
        migrations.RemoveField(
            model_name='crawledpage',
            name='requires_javascript',
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='api_endpoints',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='breadcrumb',
            field=models.JSONField(default=list, help_text='["Home", "API", "Auth"]'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='canonical_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='code_to_text_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='doc_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='doc_type',
            field=models.CharField(choices=[('api_reference', 'API Reference'), ('tutorial', 'Tutorial'), ('guide', 'Guide'), ('quickstart', 'Quick Start'), ('concept', 'Conceptual'), ('example', 'Example/Demo'), ('changelog', 'Changelog'), ('faq', 'FAQ'), ('troubleshooting', 'Troubleshooting'), ('configuration', 'Configuration'), ('migration', 'Migration Guide'), ('best_practices', 'Best Practices'), ('landing', 'Landing Page'), ('navigation', 'Navigation Page'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawler.crawledpage'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='estimated_reading_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_copy_buttons',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_examples',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_interactive_elements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_table_of_contents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_videos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='images',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='javascript_render_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='meta_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='navigation_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='og_tags',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='parameters',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='questions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='readability_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='render_method',
            field=models.CharField(choices=[('static', 'Static HTML'), ('javascript', 'JavaScript Rendered')], default='static', max_length=20),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='schema_markup',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='sections',
            field=models.JSONField(default=list, help_text='Semantic sections with headings'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='sidebar_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='table_of_contents',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='tables',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='tips',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='version_info',
            field=models.CharField(blank=True, help_text='v2.3, latest, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='warnings',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawledpage',
            name='code_blocks',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='crawledpage',
            name='content_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='crawledpage',
            name='crawled_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='crawledpage',
            name='depth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crawledpage',
            name='external_links',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='crawledpage',
            name='headers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='crawledpage',
            name='internal_links',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='crawledpage',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crawledpage',
            name='main_content',
            field=models.TextField(help_text='Cleaned text content'),
        ),
        migrations.AlterField(
            model_name='crawledpage',
            name='page_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawledpage',
            name='raw_html',
            field=models.TextField(blank=True, help_text='Original HTML for reprocessing', null=True),
        ),
        migrations.AlterField(
            model_name='crawledpage',
            name='response_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='crawledpage',
            name='status_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crawledpage',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='crawledpage',
            name='url',
            field=models.URLField(db_index=True, max_length=2000),
        ),
        migrations.AddIndex(
            model_name='crawledpage',
            index=models.Index(fields=['job', 'doc_type'], name='crawler_cra_job_id_b7a9d9_idx'),
        ),
        migrations.AddIndex(
            model_name='crawledpage',
            index=models.Index(fields=['content_hash'], name='crawler_cra_content_2efd5d_idx'),
        ),
        migrations.AddIndex(
            model_name='crawledpage',
            index=models.Index(fields=['job', 'is_duplicate'], name='crawler_cra_job_id_22305a_idx'),
        ),
        migrations.AddField(
            model_name='pagerelationship',
            name='from_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='crawler.crawledpage'),
        ),
        migrations.AddField(
            model_name='pagerelationship',
            name='to_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='crawler.crawledpage'),
        ),
        migrations.AlterUniqueTogether(
            name='pagerelationship',
            unique_together={('from_page', 'to_page', 'relationship_type')},
        ),
    ]
