# Generated by Django 5.2.8 on 2025-11-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_crawljob_core_crawlj_status_6473ab_idx_and_more'),
        ('crawler', '0002_pagerelationship_alter_crawledpage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledpage',
            name='alt_text_quality_score',
            field=models.FloatField(default=0.0, help_text='Percentage of images with meaningful alt text'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='aria_labels_count',
            field=models.IntegerField(default=0, help_text='Number of ARIA labels'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='author_bio',
            field=models.TextField(blank=True, help_text='Author credentials/bio if available'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='average_paragraph_length',
            field=models.IntegerField(default=0, help_text='Average words per paragraph'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='content_type_diversity',
            field=models.IntegerField(default=0, help_text='Number of different content types (0-5)'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='deprecation_warnings',
            field=models.JSONField(default=list, help_text='Deprecation notices'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='example_to_explanation_ratio',
            field=models.FloatField(default=0.0, help_text='Code examples vs text ratio'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='external_references',
            field=models.JSONField(default=list, help_text='Citations to authoritative sources'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_api_explorer',
            field=models.BooleanField(default=False, help_text='Has interactive API explorer'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_article_schema',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_breadcrumb_schema',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_code_playground',
            field=models.BooleanField(default=False, help_text='Has embedded code playground'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_community_comments',
            field=models.BooleanField(default=False, help_text='Has comment system'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_deprecation_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_diagrams',
            field=models.BooleanField(default=False, help_text='Contains diagrams or architecture images'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_faq_schema',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_feedback_mechanism',
            field=models.BooleanField(default=False, help_text='Has user feedback buttons'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_howto_schema',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_learning_objectives',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_next_steps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_prerequisites',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_references',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_skip_links',
            field=models.BooleanField(default=False, help_text='Has skip navigation links'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_step_by_step',
            field=models.BooleanField(default=False, help_text='Contains step-by-step instructions'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_tldr',
            field=models.BooleanField(default=False, help_text='Has TL;DR or summary section'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_troubleshooting',
            field=models.BooleanField(default=False, help_text='Has troubleshooting section'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_version_switcher',
            field=models.BooleanField(default=False, help_text='Has version switcher UI'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='heading_structure_valid',
            field=models.BooleanField(default=True, help_text='Valid h1-h6 hierarchy'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='hreflang_tags',
            field=models.JSONField(default=dict, help_text='Multi-language hreflang tags'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='imperative_sentence_count',
            field=models.IntegerField(default=0, help_text='Command sentences (Click, Run, etc.)'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='incoming_internal_links_count',
            field=models.IntegerField(default=0, help_text='Number of internal links to this page'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='is_orphan_page',
            field=models.BooleanField(default=False, help_text='No internal links pointing to it'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='language_versions',
            field=models.JSONField(default=list, help_text='Programming language version requirements'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='last_updated_text',
            field=models.CharField(blank=True, help_text='Last updated date as text', max_length=100),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='learning_objectives',
            field=models.JSONField(default=list, help_text='What user will learn'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='list_count',
            field=models.IntegerField(default=0, help_text='Number of ul/ol lists'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='mobile_viewport_meta',
            field=models.BooleanField(default=False, help_text='Has mobile viewport meta tag'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='navigation_depth',
            field=models.IntegerField(default=0, help_text='Clicks from homepage'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='next_steps',
            field=models.JSONField(default=list, help_text='Next steps after this page'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='paragraph_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='prerequisites',
            field=models.JSONField(default=list, help_text='Prerequisites and requirements'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='product_versions',
            field=models.JSONField(default=list, help_text='Product versions mentioned'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='published_date',
            field=models.CharField(blank=True, help_text='Original publication date', max_length=100),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='qa_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='qa_pairs',
            field=models.JSONField(default=list, help_text='Question-answer pairs extracted'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='reference_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='reviewed_by',
            field=models.CharField(blank=True, help_text='Technical reviewer', max_length=200),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='script_count',
            field=models.IntegerField(default=0, help_text='Number of script tags'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='sections_count',
            field=models.IntegerField(default=0, help_text='Number of major sections'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='structured_data_types',
            field=models.JSONField(default=list, help_text='Types of schema.org markup present'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='stylesheet_count',
            field=models.IntegerField(default=0, help_text='Number of stylesheet links'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='third_party_scripts',
            field=models.JSONField(default=list, help_text='Third-party script domains'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='version_compatibility',
            field=models.JSONField(default=dict, help_text='Version requirements and compatibility'),
        ),
        migrations.AlterField(
            model_name='crawledpage',
            name='author',
            field=models.CharField(blank=True, help_text='Article author', max_length=200),
        ),
        migrations.AddIndex(
            model_name='crawledpage',
            index=models.Index(fields=['job', 'has_references'], name='crawler_cra_job_id_90b622_idx'),
        ),
        migrations.AddIndex(
            model_name='crawledpage',
            index=models.Index(fields=['job', 'qa_count'], name='crawler_cra_job_id_4ca4d9_idx'),
        ),
        migrations.AddIndex(
            model_name='crawledpage',
            index=models.Index(fields=['job', 'has_prerequisites'], name='crawler_cra_job_id_1c1b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='crawledpage',
            index=models.Index(fields=['job', 'content_type_diversity'], name='crawler_cra_job_id_7c9143_idx'),
        ),
        migrations.AddIndex(
            model_name='crawledpage',
            index=models.Index(fields=['job', 'is_orphan_page'], name='crawler_cra_job_id_9553c2_idx'),
        ),
        migrations.AddIndex(
            model_name='crawledpage',
            index=models.Index(fields=['job', 'has_deprecation_warning'], name='crawler_cra_job_id_b28fbd_idx'),
        ),
        migrations.AddIndex(
            model_name='crawledpage',
            index=models.Index(fields=['job', 'sections_count'], name='crawler_cra_job_id_33e38a_idx'),
        ),
    ]
