# Generated by Django - Adds client field to CrawledPage for client-level deduplication

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('crawler', '0003_crawledpage_alt_text_quality_score_and_more'),
    ]

    operations = [
        # Add client field (nullable initially)
        migrations.AddField(
            model_name='crawledpage',
            name='client',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='pages',
                to='core.client'
            ),
        ),
        
        # Remove old unique constraint
        migrations.AlterUniqueTogether(
            name='crawledpage',
            unique_together=set(),
        ),
        
        # Add index for client
        migrations.AddIndex(
            model_name='crawledpage',
            index=models.Index(fields=['client', 'crawled_at'], name='crawler_cra_client__idx'),
        ),
    ]
