# Generated by Django 5.2.8 on 2025-11-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_make_client_non_nullable'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='crawledpage',
            new_name='crawler_cra_client__31735a_idx',
            old_name='crawler_cra_client__idx',
        ),
    ]
