# Generated by Django 5.2.8 on 2025-11-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_add_embeddings_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledpage',
            name='ai_analysis_metadata',
            field=models.JSONField(default=dict, help_text='{model, timestamp, confidence_scores, processing_time}'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='ai_learning_objectives',
            field=models.JSONField(default=list, help_text='[{objective, bloom_level, domain, difficulty}] - structured LOs'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='ai_prerequisite_chain',
            field=models.JSONField(default=list, help_text='[{concept, type, importance, urls}] - linked prerequisites'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='ai_topics',
            field=models.JSONField(default=list, help_text='[{name, relevance, parent, children, related}] - hierarchical topics'),
        ),
    ]
