# Generated by Django 5.2.8 on 2025-11-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0010_add_ai_analysis_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledpage',
            name='ai_audience_level',
            field=models.CharField(blank=True, default='', help_text='AI-classified audience level: beginner, intermediate, advanced', max_length=20),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='ai_doc_type',
            field=models.CharField(blank=True, default='', help_text='AI-classified doc type using Diátaxis framework', max_length=30),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='ai_key_concepts',
            field=models.JSONField(default=list, help_text='[{term, definition, is_new}] - key concepts introduced or used'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='ai_quality_indicators',
            field=models.JSONField(default=dict, help_text='{completeness_score, needs_code_examples, needs_visuals, suggested_improvements}'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='ai_related_topics',
            field=models.JSONField(default=list, help_text='List of related topic strings for cross-linking'),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='ai_summary',
            field=models.TextField(blank=True, default='', help_text='AI-generated 1-2 sentence summary for clustering'),
        ),
        migrations.AlterField(
            model_name='crawledpage',
            name='ai_analysis_metadata',
            field=models.JSONField(default=dict, help_text='{model, timestamp, processing_time_seconds, content_length}'),
        ),
        migrations.AlterField(
            model_name='crawledpage',
            name='ai_learning_objectives',
            field=models.JSONField(default=list, help_text='[{objective, bloom_level, bloom_verb, difficulty, estimated_time_minutes, measurable}] - structured LOs'),
        ),
        migrations.AlterField(
            model_name='crawledpage',
            name='ai_prerequisite_chain',
            field=models.JSONField(default=list, help_text='[{concept, type, importance, description}] - linked prerequisites'),
        ),
        migrations.AlterField(
            model_name='crawledpage',
            name='ai_topics',
            field=models.JSONField(default=list, help_text='[{name, relevance, category, parent_topic, child_topics, related_topics}] - hierarchical topics'),
        ),
    ]
