# Generated by Django 5.2.8 on 2025-11-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0011_add_enhanced_ai_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledpage',
            name='learning_objective_embeddings',
            field=models.JSONField(default=list, help_text='[{objective, bloom_level, difficulty, embedding}] - embeddings for each learning objective'),
        ),
    ]
