# Generated by Django 5.2.8 on 2025-11-16 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('summary', 'Executive Summary'), ('detailed', 'Detailed Analysis Report'), ('comparison', 'Comparison Report'), ('custom', 'Custom Report')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField(default=dict, help_text='Report content and sections')),
                ('file_path', models.CharField(blank=True, help_text='Path to generated PDF/HTML', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.crawljob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
