# Generated by Django 5.2.8 on 2025-11-16 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('structure', 'Documentation Structure Analysis'), ('content_gaps', 'Content Gap Detection'), ('api_completeness', 'API Reference Completeness'), ('tutorial_quality', 'Tutorial Quality Assessment'), ('custom', 'Custom Analysis')], max_length=50)),
                ('results', models.JSONField(default=dict, help_text='Analysis results and insights')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='core.crawljob')),
            ],
            options={
                'verbose_name_plural': 'Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
